### PR TITLE
Add Firebase authentication(Email and Google SignIn)

### PR DESCRIPTION
**Pull request by mecca1991**
The Firebase Authentication screen is made with Firebase-UI

### CODE REVIEW

**Comment by divanydio** [comment]
@chetat  good job,
but the authentification with Google is not working,
look at your firebase account for this project and check your parameters (eg: SHA1 or support email) and check the activation of Google auth , please

**Comment by mecca1991** [comment]
> @chetat good job,
> but the authentification with Google is not working,
> look at your firebase account for this project and check your parameters (eg: SHA1 or support email) and check the activation of Google auth , please

**Comment by mecca1991** [comment]
Hi, do you receive an error when trying to authenticate? I tested several times on emulator and it was working. Please let me know the error that you are having on your logcat

**Comment by divanydio** [comment]
the error is represented by the Toast diplay saying that the **Code 10**

**Comment by divanydio** [comment]
this error occur when there is an error in the firebase project configuration params or in the Google Auth  config

**Comment by divanydio** [comment]
Hi @chetat

**Comment by mecca1991** [comment]
> Hi @chetat
Hi @divanydio! I tried on another real device and I still don't get the **Code 10**

**Comment by mecca1991** [comment]
I just reconfigured the firebase app and it is still working fine. Can you reinstall again and let me know?

**Comment by Ora-Kool** [comment]
The Auth is not working. when i tried to login with google, i get

**2019-10-22 11:52:53.056 19121-19121/com.andela.dairyapp W/GoogleSignInHandler: Developer error: this application is misconfigured. Check your SHA1 and package name in the Firebase console.
2019-10-22 11:52:53.057 19121-19121/com.andela.dairyapp E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
        at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:110)
        at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onActivityResult(AuthMethodPickerActivity.java:325)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-10-22 11:52:53.058 19121-19121/com.andela.dairyapp E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
        at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:110)
        at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onActivityResult(AuthMethodPickerActivity.java:325)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-10-22 11:52:53.064 19121-19168/com.andela.dairyapp V/FA: Activity resumed, time: 8390139
2019-10-22 11:52:53.092 19121-19168/com.andela.dairyapp D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=SignInHubActivity, ga_previous_id(_pi)=-6999918850789514572, ga_screen_class(_sc)=AuthMethodPickerActivity, ga_screen_id(_si)=-6999918850789514575}]
2019-10-22 11:52:53.134 19121-19168/com.andela.dairyapp V/FA: Connecting to remote service
2019-10-22 11:52:53.138 19121-19168/com.andela.dairyapp V/FA: Connection attempt already in progress
2019-10-22 11:52:53.142 19121-19168/com.andela.dairyapp D/FA: Connected to remote service
2019-10-22 11:52:53.143 19121-19168/com.andela.dairyapp V/FA: Processing queued up service tasks: 2
2019-10-22 11:52:58.169 19121-19168/com.andela.dairyapp V/FA: Inactivity, disconnecting from the service**

**Comment by mecca1991** [comment]
Did you Uninstall the previous version and reinstall it? Because you need to reinstall it. also make sure you pulled the latest version of the code.

**Comment by Ora-Kool** [comment]
> Did you Uninstall the previous version and reinstall it? Because you need to reinstall it. also make sure you pulled the latest version of the code.

i did fetch your branch which you created chetat:firebase_auth to my local and run it to test your implementations

**Comment by Ora-Kool** [comment]
I have just uninstalled it and i still get the     com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10:

**Comment by Ora-Kool** [comment]
And also the app doesn't close when you are on the AuthActivity, that is if you want to navigate back. it just reopen the AuthActivity.

**Pull request merged**
