### PR TITLE
Deploy recyclerview animation pull request to resolve #24

### LINKED ISSUE #24: Animate the RecyclerView Scroll behavior using a third party library
I think applying the scale in animation on the recycler adapter as shown in the app will be a cool feature

### PR DESCRIPTION
**Pull request by BonyaO**

### CODE REVIEW

**Comment by Ora-Kool** [comment]
Youhave to create a branch for this implementation since it is an animation.

**Comment by BonyaO** [comment]
I created a local branch "deploy-recyclerview-animation", it's also in my
GitHub handle. I thought pushing it will send the branch info to our main
GitHub project. How can go I go about that?

**Comment by BonyaO** [comment]
I just got some info on how to go about that. Let me follow through

**Comment by Ora-Kool** [comment]
Ask that question in the slack team.

**Comment by divanydio** [comment]
But for the moment, this branch is not in the current repository,

**Comment by divanydio** [comment]
I think that , is you add another **origin**(eg: call origin-aad-team) branch in your project pointing on this repository, you can push your **deploy-recyclerview-animation** branch in this repository

**Comment by divanydio** [comment]
try : 
1. git remote add origin-add-team https://github.com/Ora-Kool/aad-team-6-animation-challenge.git
2. git push **origin-add-team** **deploy-recyclerview-animation**

**Comment by kkyb123** [comment]
I think @BonyaO is doing the right thing. Even instruction **8** from the instructions says this:

Every animation added should have a different branch and a pull request should be made and the team lead will then merge it to deploy branch after verifying the code. 

He created the new branch and the PR. The new branch he created will be recorded if we merge the code. So let's review the code and functionality and if it is ok we should approve and merge the PR

**Comment by divanydio** [comment]
@BonyaO  , i pull your code and the recyclerview is not animated,

**Comment by divanydio** [comment]
@BonyaO , only the slide_in_right.xml file is define in your code

**Comment by divanydio** [comment]
Check your code again and apply the your animation on the View of your choice

**Comment by divanydio** [comment]
@BonyaO , a third party library is not required in this challenge 
(    implementation 'jp.wasabeef:recyclerview-animators:3.0.0' ) is not need here

**Comment by divanydio** [comment]
I'm going to merge this PR because it's include animated splash screen and recycleView animation(steel to be review later 
)

**Comment by BonyaO** [comment]
I'm sorry about the third party library issue, I thought we could use any
of the the methods shown in the animation course.

**Pull request merged**
